### PR TITLE
Fixed issue #488: `npm run dev` race condition

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by amilajack** [comment]
@chentsulin @jhen0409 would be great if you could test this out locally just to be safe.

**Comment by jhen0409** [comment]
I hope it can be continuously output logs of main process, so it should use `spawn`, just like [better-npm-run](https://github.com/benoror/better-npm-run/blob/master/lib/exec.js) usage.

Also, currently I still prefer to separate `hot-server` and `start-hot`, because I often change the main process, and no restart webpack server, it's even better if it can be used as an option for `hot-server`. 👍

**Comment by amilajack** [comment]
@jhen0409 the main process still does output logs.

> Also, currently I still prefer to separate hot-server and start-hot, because I often change the main process, and no restart webpack server

Those commands still exist. Actually `npm run dev` still uses them.

**Comment by jhen0409** [comment]
> the main process still does output logs.

No, the logs will not be output continuously if we used `child_process.exec`.

Try `setInterval(() => console.log('hey'), 100)` on main process.

> Those commands still exist. Actually npm run dev still uses them.

I mean we can provide an option for `hot-server`, currently if I just run `npm run hot-server` it will start Electron app for this PR.

**Comment by amilajack** [comment]
I'm testing `spawn` locally like this:

```
```

**Comment by jhen0409** [comment]
@amilajack, just try the following code, it's works well for me:

```js
spawn('npm', ['run', 'start-hot'], { stdio: 'inherit' })
  .on('close', code => {
    process.exit(code);
  })
  .on('error', _error => {
    console.error(_error);
  });
```

Because it will check `npm` command exists, not `npm run start-hot`.

Also, see https://github.com/benoror/better-npm-run/pull/24 and https://github.com/benoror/better-npm-run/pull/46, I think `stdio: 'inherit'` will be better here, unless we want to add additional characters to each output.

**Comment by amilajack** [comment]
Fixed. What's the flag option that we should add? I don't understand that fully

**Comment by jhen0409** [comment]
@amilajack, see https://github.com/chentsulin/electron-react-boilerplate/pull/162#issuecomment-190619469, I would like to have a way to open the webpack server only, and we have #341, so I think restart the app and keep the server running will be more convenient. I expected it on `npm run hot-server`, what do you think?

**Comment by amilajack** [comment]
>  I expected it on npm run hot-server

Can you show me an example/pseudo code for this? Still not sure if I get you 100%. I know that you want to be able to restart both the webpack and the app separately. But when you say `I expected it on npm run hot-server`, I'm confused. Didn't we already do this by starting `npm run start-hot` in `server.js`, which runs when `npm run hot-server` is called?

**Comment by jhen0409** [comment]
@amilajack, I mean `open webpack server *only*` on `npm run hot-server`, but this PR doesn't do, it affected [the first usage of README](https://github.com/chentsulin/electron-react-boilerplate#run).

I think we need a flag option is just like:

```json
"dev": "npm run hot-server -- --start-hot",
```

**Comment by amilajack** [comment]
@jhen0409 ready to merge?

**Comment by jhen0409** [comment]
OK, merged. :D

**Pull request merged**
