### PR TITLE
add .nvmrc file

### PR DESCRIPTION
**Pull request by cmbirk**
This just adds the last release for node 6.* in the `.nvmrc` file

### CODE REVIEW

**Comment by cmbirk** [comment]
Fixes #725

**Comment by amilajack** [comment]
Is there a way to allow nvm to use any version >= 6.0.0?

**Comment by cmbirk** [comment]
Not that I'm aware of.  The idea is to specify the latest node version that this supports and remove ambiguity.

**Comment by amilajack** [comment]
Thanks!

**Pull request merged**
