### PR TITLE
v0.13.0

### PR DESCRIPTION
**Pull request by amilajack**
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/1045
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/1159

### CODE REVIEW

**Comment by Unforgiven-wanda** [comment]
Is there a release date for this?

**Comment by amilajack** [comment]
Can't merge this until CI passes. Not sure why its failing

**Comment by andrewcl** [comment]
Is there a status on when this might be released? It seems there are a few fixes in 0.13.0 that might resolve the issues I'm encountering w/ 0.12.0

**Comment by amilajack** [comment]
Will be released soon. Feel free to checkout the branch and start using `v0.13.0`

**Pull request merged**
