### PR TITLE
Add electron-redux module

### PR DESCRIPTION
**Pull request by dustintownsend**
This uses the proposed changed in PR #602. 
I have the need for syncing the state between main and renderer, so this is my first pass. Based on the discussion from Issue #108 I decided to try https://github.com/hardchor/electron-redux/ first. I may do another PR for redux-electron-store and an alternative.

@burkhardr can you look over this and see if I got any of the implementation wrong? I based it on your timesheets repo.

### CODE REVIEW

**Comment by hardchor** [comment]
@dustintownsend Hey. Nothing glaringly obvious I can spot. 
Most importantly: does it work? 😉

**Comment by hardchor** [comment]
Might be worth adding some examples of, e.g. async actions, local or aliased actions.

**Comment by dustintownsend** [comment]
@hardchor do you have any insight into why the test are failing?

It is failing at replyActionMain.js at ipcMain.on. It seems that ipcMain is not importing. I assume its due to not being in electron but a test, but I don't know enough about testing to be 100%.

**Comment by jhen0409** [comment]
> It is failing at replyActionMain.js at ipcMain.on. It seems that ipcMain is not importing. I assume its due to not being in electron but a test, but I don't know enough about testing to be 100%.

https://github.com/chentsulin/electron-react-boilerplate/issues/573#issuecomment-263033090 have provided a workaround, maybe we can migrate to `electron-mocha` (although we have #520), but it will broken `test-watch` (A reason is https://github.com/jprichardson/electron-mocha/pull/18).

**Comment by hardchor** [comment]
If this is a unit test, you'll probably need to mock `electron`. It's slightly confusing that `electron` is now also the name of `electron-prebuilt` on npm, so whilst running tests, that'll probably be imported (rather than the actual electron helpers).

**Comment by dustintownsend** [comment]
I'm going to close this for now. I'm not sure this is a good fit for the boilerplate right now. I think it would be better as an optional add on.

**Comment by hardchor** [comment]
What are the core maintainer's thoughts? I could have another go at this once the jest PR is in.

/cc @jhen0409 @amilajack

**Comment by amilajack** [comment]
I'm not very experienced with redux. @jhen0409 and @chentsulin may have more to say about this

**Pull request closed without merging**
