### PR TITLE
First effort towards moving to redux

### PR DESCRIPTION
**Pull request by chentsulin**
out1

### CODE REVIEW

**Comment by catalinmiron** [comment]
@chentsulin this subject it's quite interesting. Can I help you somehow?

**Comment by chentsulin** [comment]
I thought the only thing block this is waiting release of react-router@1 and redex-devtools@3. It seems react-router will release 1.0 this month, anyway, I will release a beta version maybe today or tomorrow.

**Comment by chentsulin** [comment]
beta version: https://github.com/chentsulin/electron-react-boilerplate/releases/tag/v0.7.0-beta

**Comment by shea256** [comment]
Hi I'm having an issue with data persistence. It is neither working in the development or the production build? Any ideas what might be going wrong?

I'm also considering going with the simpler `localStorage.setItem` and ripping out Redux. Any guidance on to why or why not would be greatly appreciated.

Of course, if I'm able to get up and running soon with Redux persisting data after application close, I'll reconsider.

**Comment by chentsulin** [comment]
It's really simple to use redux with data persistence, just prepare your store's state from `localStorage`, your files or some other databases (sqlite, leveldb...and so on), and also sync your storage when  store's state changed.

You can get some ideas from:
- https://github.com/elgerlambert/redux-localstorage
- https://gist.github.com/HeyImAlex/0f5ee73e581f64b6c290

**Comment by shea256** [comment]
Awesome, thank you @chentsulin! `redux-localstorage` is great, got it working in a minute.

**Pull request merged**
