### PR TITLE
Add update-electron-app using electron-updater

### LINKED ISSUE #1514: Investigate: update-electron-app
See [https://github.com/electron/update-electron-app](https://github.com/electron/update-electron-app)

### PR DESCRIPTION
**Pull request by talmukund**
This should resolve #1514

### CODE REVIEW

**Comment by amilajack** [comment]
I'll try to get this into `v0.14.0`

**Comment by amilajack** [comment]
Thanks for this 🎉 🎉 🎉

**Comment by amilajack** [comment]
I just realized that this PR doesn't actually use `update-electron-app`

**Comment by talmukund** [comment]
Electron-builder provides better api for auto-update than default electron's auto updater.

**Comment by alirezavalizade** [comment]
I couldn't see these changes on master branch!

**Comment by amilajack** [comment]
Reverted them. They didn’t work

**Comment by alirezavalizade** [comment]
Do you have any suggestion for updating on this boilerplate? @amilajack

**Pull request merged**
