### PR TITLE
Added node-loader suppport

### PR DESCRIPTION
**Pull request by amilajack**
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/813

### CODE REVIEW

**Comment by amilajack** [comment]
I think we should also add `json-loader` while we're at this. Its pretty common as well

**Comment by jhen0409** [comment]
I think this will still not work for #812 or #807, [like `serialport` use `bindings` to load `node` file](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/master/lib/bindings/darwin.js#L2) (and auto detect platform), I'm recommended just add to `app/package.json`.

> I think we should also add json-loader while we're at this. Its pretty common as well

`json-loader` is work on webpack 2 by [default](https://github.com/webpack-contrib/json-loader#json-loader), this is why [#769](https://github.com/chentsulin/electron-react-boilerplate/commit/830e2e876c780b58880680613e112679ab40c3de#diff-d9d75cc1dda9c5e912390983ac6b263aL17) removed it.

**Comment by Slapbox** [comment]
Too funny. I just asked about this in Gitter. This seems to happen often.

**Comment by Slapbox** [comment]
I get the following when I run that `webpack.config.base.js`

```
[1] "use" is not allowed
[2] "value" must contain at least one of [loaders, loader]
```

**Comment by amilajack** [comment]
You're probably using webpack 1. Try pulling the upstream if you set it to this boilerplate

**Comment by Slapbox** [comment]
Ah nevermind I didn't realize we had updated to Webpack 2 now. I will have to do some work to catch up.

**Pull request closed without merging**
