### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by ocboogie**
`*`: To be changed in the future
`-`: Declined future change
`+`: Changed
`=`: Need to be discussed

## General
  * +Move all prod build files to the build folder
  * *Move main and renderer source files to different folders
  * *Move webpack configs to internals with prod and dev subfolder
  * =Change comma-dangle in eslint
  * +Fix Import order
  * +Clean up path.join/path.resolve
  * =Fix non default imports. For example
  ```js
  import path from 'path'
  // path has no default export so we would want to use
  import * as path from 'path'

  ```
### `webpack.config.main.prod.js`
  * +Remove: 
  ```js
    process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'
  ```

### `webpack.config.renderer.prod.js`
  * +Remove:
  ```js
    move new webpack.DefinePlugin({
        process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production')
    })
  ```

### CODE REVIEW

**Comment by ocboogie** [comment]
Should I do a pull request on the master or #1166?

**Comment by amilajack** [comment]
@ocboogie This PR is a little outdated. Can you please make the same PR against the `v0.13.3` branch?

**Comment by ocboogie** [comment]
Alright let me work on this

**Comment by amilajack** [comment]
Closing due to inactivity

**Pull request closed without merging**
