### PR TITLE
Webpack Image Support

### PR DESCRIPTION
**Pull request by amilajack**
**DO NOT MERGE. IN PROGRESS**

### CODE REVIEW

**Comment by jhen0409** [comment]
We already have `svg` load in [renderer config](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.production.js#L50).

**Comment by amilajack** [comment]
What do you think about moving these changes to the renderer instead?

**Comment by amilajack** [comment]
@jhen0409 would be great if you could review

**Comment by jhen0409** [comment]
> What do you think about moving these changes to the webpack renderer config instead?

Yeah I think we should moving these changes to renderer config, because main process may not need it.

Also I think we can have renderer base config for `development` and `production` on [`webpack.config.base.js`](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.base.js).

**Comment by amilajack** [comment]
@jhen0409 Made my changes. Do they reflect what you described?

**Pull request merged**
