### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by amilajack**
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/808 https://github.com/chentsulin/electron-react-boilerplate/issues/833 #909 #905 #874 https://github.com/chentsulin/electron-react-boilerplate/issues/872

Remember to mark off https://github.com/chentsulin/electron-react-boilerplate/issues/504

### CODE REVIEW

**Comment by uppe-r** [comment]
Hey amila, just tested it on a fresh clone and everything was working as supposed to!

**Comment by amilajack** [comment]
@uppe-r of dev-master or master?

**Comment by uppe-r** [comment]
dev-master

**Comment by amilajack** [comment]
@williamoliveira @uppe-r found an issue when reloading after navigating to a certain route. To reproduce, click on 'counter' and reload.

**Comment by uppe-r** [comment]
@amilajack You're right. This happened to me before and I kinda ignored it since I was testing the old content loading bug.

Probably has something to do with #884?

**Comment by williamoliveira** [comment]
master was using a hash router, on dev-master its an html5 one

**Comment by amilajack** [comment]
@williamoliveira +1 for a PR :)

**Pull request merged**
