### PR TITLE
Added appveyor support

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by jhen0409** [comment]
👍

We can consider add `os: unstable` option it's recommend by [spectron](https://github.com/electron/spectron#on-appveyor).

/cc @chentsulin

**Comment by amilajack** [comment]
Fixed

**Comment by chentsulin** [comment]
Maybe we can cache `node_modules` folder as what we does with travis?

https://github.com/chentsulin/electron-react-boilerplate/blob/master/.travis.yml#L10

**Comment by amilajack** [comment]
Added caching support

**Comment by amilajack** [comment]
Also remember to enable the tests at https://www.appveyor.com

**Pull request merged**
