### PR TITLE
Revert "Update babili-webpack-plugin to version 0.0.8 🚀"

### PR DESCRIPTION
**Pull request by amilajack**
Reverts chentsulin/electron-react-boilerplate#670

### CODE REVIEW

**Comment by jhen0409** [comment]
I realized that problem might be from `babel-plugin-minify-dead-code-elimination@0.1.2` (`0.1.1` works fine), so it will still not work even if we reverted the webpack plugin version.

**Comment by amilajack** [comment]
What about temporarily disabling babli?

**Comment by amilajack** [comment]
Merging because of https://github.com/chentsulin/electron-react-boilerplate/issues/672#issuecomment-274996314. I also confirmed this with my own local revert

**Comment by jhen0409** [comment]
We must ensure CI is passing.. I guess somebody are still use `babel-plugin-minify-dead-code-elimination@0.1.1` because yarn lock, we can get `0.1.2` by npm, or `yarn upgrade`.

I'll submit a better temporarily fix for that.

**Comment by amilajack** [comment]
This seems to have fixed it. See https://travis-ci.org/chentsulin/electron-react-boilerplate/builds/195083218, which is a test of a branch that has this change. It seemed like the cache was outdated

**Comment by jhen0409** [comment]
@amilajack looks like this passed build is still used 0.1.1. (see [this line](https://github.com/chentsulin/electron-react-boilerplate/blob/e46f10d5bda20761f27547df355541b9db81e90d/yarn.lock#L593))

**Pull request merged**
