### PR TITLE
Fix router

### PR DESCRIPTION
**Pull request by anthonyraymond**
Since `ConnectedRouter` has been introduced, `history.push` `history.goBack` and any other`history` function has no effect on the rendering process (but dispatch actions properly ).

This probably happens because there are two router nested `HashRouter` from *app/routes.js* is nested into `ConnectedRouter` from *app/containers/Root.js*

How to reproduce:
**app/Home.js**
```
// @flow
import React, { Component } from 'react';
import styles from './Home.css';
import { history } from '../store/configureStore';

export default class Home extends Component {
  render() {
    return (
      <div>
        <div className={styles.container} data-tid="container">
          <h2>Home</h2>

          <button onClick={() => { history.push('/counter'); }}>
            test
          </button>
        </div>
      </div>
    );
  }
}

```

### CODE REVIEW

**Comment by amilajack** [comment]
@anthonyraymond changed the base of the PR to release `v0.11.2`. Would be great if you could resolve the merge conflicts

**Comment by anthonyraymond** [comment]
Should be ok. I used the online user-friendly "Resolve button". Didn't knew that ever exists x)
I hope this will work. Otherwise i'll do a manual commit tonight

**Comment by amilajack** [comment]
@Slapbox Would really appreciate if you could test this out before merging into `v0.11.2`

**Comment by Slapbox** [comment]
I implemented it without issue in my app, but I'm not actively using the router. I am 100% single paged, so my test case is very weak, just loading my main page and then not routing again.

**Comment by Slapbox** [comment]
By the way, since it's related to router, worth mentioning it has no effect on #935 for me.

**Comment by amilajack** [comment]
This is the most annoying thing about the JS ecosystem (and probably other language ecosystems). You change on upgrade some dependency and you find out later that something broke (and you have no idea why).

**Comment by Slapbox** [comment]
Much truth. Dependency hell has been made a lot less terrible by Yarn, but it still exists in its own way.

**Comment by amilajack** [comment]
Sorry for the delay on this. Wanted to take the time to do some testing myself

**Comment by anthonyraymond** [comment]
No problem :)
Thabks for the merge

**Pull request merged**
