### PR TITLE
Upgrade to react-hot-loader 3 from react-transform

### PR DESCRIPTION
**Pull request by tyscorp**

### CODE REVIEW

**Comment by jhen0409** [comment]
We should not be required `react-hot-loader` in the production, maybe we can separate to `.prod.js` and `.dev.js`, or just a `NODE_ENV` check?

**Comment by tyscorp** [comment]
I think that AppContainer and the entry patch amount to a noop when NODE_ENV is production by default.

**Comment by jhen0409** [comment]
@tyscorp oh, indeed. lol

But it will still saved [some code](https://github.com/gaearon/react-hot-loader/blob/next/src/index.js) for not `require('react-hot-loader')`, though not many.

**Comment by chentsulin** [comment]
We will revisit this PR after react-hot-loader v3 release!

**Comment by madc** [comment]
@tyscorp I've implemented this functionality based on this PR in my project and it works in development env. But when running in production (`npm run build` && `npm run start`) I get the following:

```bundle.js:1 Uncaught ReferenceError: AppContainer is not defined```

Does this work for you?

**Comment by amilajack** [comment]
What is the difference between react-hot-loader 3 and react-transform?

**Comment by amilajack** [comment]
@tyscorp can you please rebase this PR

**Comment by amilajack** [comment]
Closing, as `react-transform` has been deprecated

**Pull request closed without merging**
