### PR TITLE
Switch mocha to jest

### PR DESCRIPTION
**Pull request by akozhemiakin**
This commit replaces mocha with jest. Also this commit removes dependency on
babel-plugin-webpack-loaders plugin because of the following reasons:
1. It seems that the author deprecated and abandoned this plugin and he suggests
not to use it and to use mocks and native test utilities tools instead.
2. This plugin conflicts with webpack 2 and because of the reason one it is unlikely
that it will ever support it.

In order to remove dependency on the aforementioned plugin and keep using css
modules in the same time the following trick is used: All components that need to
be selected in the end-to-end test receive data-tid (TestID) and data-tclass
(TestCLASS) properties. It is necessary because without running webpack we can't
use class names to select components because we do not know what class names
css loader actually generates for us.

P.S. I prepared upgrade to webpack 2 but it depends on this commit. So after this PR is closed I'll create pull request for webpack upgrade.

### CODE REVIEW

**Comment by jhen0409** [comment]
Could you also change `test/example.js`? Has [lint errors in AppVeyor build](https://ci.appveyor.com/project/chentsulin/electron-react-boilerplate/build/1406/job/c1siw00d33rsu85a#L1692), I guess Travis CI passed because `node_modules` cache.

**Comment by akozhemiakin** [comment]
I fixed example.js but it seems that appveyor has some other reason to fail. I got very similar error one time and fixed it by deleting node_modules directory and reinstalling project. Do not know however how to fix appveyor.

**Comment by jhen0409** [comment]
Actually @amilajack was do #613, we have the same problem on AppVeyor. :\

**Comment by akozhemiakin** [comment]
Maybe it expects \ instead of / ? Apveyor runs on windows after all.

**Comment by akozhemiakin** [comment]
Hooray! I fixed it )

**Comment by akozhemiakin** [comment]
Done. I believe I remove all references to mocha.

**Comment by amilajack** [comment]
@akozhemiakin LGTM!

**Comment by akozhemiakin** [comment]
Nice. Know @amilajack you can fill another checkbox here #504 (:

**Comment by amilajack** [comment]
Done!

**Pull request merged**
