### PR TITLE
Added `npm run package` to ci tests

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by chentsulin** [comment]
Should add `sudo: required` to travis-ci.

https://docs.travis-ci.com/user/ci-environment/

**Comment by jhen0409** [comment]
I'm suggest add packages to [addons.apt.packages](https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages) for keep the same code.

**Comment by amilajack** [comment]
So `sudo:false` or `sudo:required`?

**Comment by amilajack** [comment]
I think we should stick with `sudo:false`

**Comment by amilajack** [comment]
What is the status of this PR?

**Comment by jhen0409** [comment]
@amilajack If we want to keep `sudo: false`, you should move the apt packages installation to [addons.apt.packages](https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages).

**Comment by amilajack** [comment]
@jhen0409 @chentsulin Fixed.

**Comment by chentsulin** [comment]
@amilajack Thanks 👍

**Pull request merged**
