### PR TITLE
fix window is undefined #385

### PR DESCRIPTION
**Pull request by ArnaudValensi**

### CODE REVIEW

**Comment by amilajack** [comment]
I can't figure out why this fixes it. Can you please explain this. Thanks!

**Comment by ArnaudValensi** [comment]
The modification was originally suggested by @worldjoe [here](https://github.com/chentsulin/electron-react-boilerplate/issues/385#issuecomment-249276167)

Here is my understanding:

When we create a npm module, in the `package.json` we can add different entry points to use a module in different contexts, like as node module, browser, etc.

Here is the `package.json` of `form-data`:
```
...
  "main": "./lib/form_data",
  "browser": "./lib/browser",
...
```

`resolve.packageMains` seems to tell webpack what entry point pack.

**Comment by amilajack** [comment]
I see. Have you tried testing this on your local machine? Also I think it would be better if you could merge this into the new `dev-master` branch so that I can test this out. Thanks!

**Comment by ArnaudValensi** [comment]
Yes, I tried it. Actually I had the issue and I was looking for a solution to put my software in production.

**Comment by ArnaudValensi** [comment]
@amilajack I don't see any `dev-master` branch.

**Comment by amilajack** [comment]
Sorry about that. Forgot to push from my local env. You should see it now.

**Comment by ArnaudValensi** [comment]
I've made another PR into dev-master here: https://github.com/chentsulin/electron-react-boilerplate/pull/436

**Pull request closed without merging**
