### PR TITLE
Use handlebars for main app page.

### PR DESCRIPTION
**Pull request by knpwrs**
Just a thought. If this were to be merged there may be a discussion around how much logic you want in the template vs in the variables being passed to the template.

### CODE REVIEW

**Comment by amilajack** [comment]
why?

**Comment by knpwrs** [comment]
It's just a different way to do things. It doesn't really matter. I only found out about the APIs for intercepting the file protocol earlier today and thought it was cool (after seeing applications for pug and ejs templates).

**Comment by amilajack** [comment]
I don't really think this dependency is worth its weight. Its better to use idiomatic JS IMO.

**Comment by knpwrs** [comment]
Fair enough. Probably fits better in an application that already uses Handlebars.

**Comment by amilajack** [comment]
Yup, exactly what I was thinking!

**Comment by amilajack** [comment]
Should this be closed then?

**Comment by knpwrs** [comment]
May as well. I typically let the repo owner weigh in.

**Pull request closed without merging**
